### ISSUE TITLE
IOException while awaiting document conversion

### ISSUE THREAD

**Issue by clinically-au** [gologicgroup/notifyre-dotnet-sdk#4]
Hi

I'm testing Fax Sending using the current version of the library (1.1) using a simple console test app and using the example code from the docs. 

I am getting an error while the library is waiting for document conversion. In FaxSendService.cs, ObserveDocumentStatus, the status never changes from "initialised" and eventually calls to GetDocumentStatusAsync throw an exception with:

System.Net.Http.HttpRequestException: An error occurred while sending the request.
 ---> System.IO.IOException: Unable to read data from the transport connection: An existing connection was forcibly closed by the remote host..
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.

Do you have a working demo of the fax send api or any tips on troubleshooting?

**Comment by gologic-mike** [comment]
Thanks @wojtj - this was actually due to a config issue on the backend which was preventing the document conversion status from being updated, should be resolved now.
